cd %1
echo Building Compilation.hs...
ghc -package ghc -package safe-exceptions -package split -c -no-hs-main -g2 -O Compilation.hs -fforce-recomp
echo Building HSCodeGen.cpp...
ghc -optcxx-fpermissive -O -c HSCodeGen.cpp
echo Linking library...
ghc -package ghc -package split -package safe-exceptions -no-hs-main -shared -g2 -o %2/HSCodeGen.dll Compilation.o HSCodeGen.o